### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-2-Gordiychuk-O-P** [UMSF-K13-2-Gordiychuk-O-P/UMSF-K13-2-Gordiychuk-O-P-MainProject#2]
![default](https://cloud.githubusercontent.com/assets/19576477/15635047/d2975b6e-25dc-11e6-907f-d14e64055839.JPG)

**Comment by smoktii-igov** [comment]
Не выставлены  лабелс, но в целом нормально
